### PR TITLE
RHMAP-10098 Update to Swift 2.3

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych can you take a look?

**Comment by corinnekrych** [comment]
@jcesarmobile swift2.3 branch will be better

**Comment by jcesarmobile** [comment]
done

**Comment by matzew** [comment]
I did the following:
- `gcl`
- `gco swift2.3`
- `pod install`
- `open blank-ios-app.xcworkspace`

It still asks me about converting to Swift 2.3  and than mentiones frameworks - is this expected ?

**Comment by matzew** [comment]
Note, I am on CocoaPods 1.1.1 and xcode8.1

**Comment by corinnekrych** [comment]
On CocoaPods 1.1.1 we need to use .swift-version
We have a JIRA for it: 
let me try it with cocoapods 1.1.1

**Comment by matzew** [comment]
> On CocoaPods 1.1.1 we need to use .swift-version

@corinnekrych not sure I understand that

BTW. whats the JIRA number?

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
